spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/stensrud
spring.datasource.username=Terje
spring.datasource.password=ronnes
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect